class_name LocalizationData
extends RefCounted

# AUTO-GENERATED — do not edit by hand.
# Source: res://localization/game_text.csv
# Regenerate with: godot --headless --script res://scripts/tools/GenerateLocalizationData.gd

const TRANSLATIONS: Dictionary = {
	"en": {
		"ui.common.close": "Close",
		"ui.common.buy": "Buy",
		"ui.common.cost": "Cost",
		"ui.common.reward": "Reward",
		"ui.common.level": "Level",
		"ui.common.cleared": "Cleared",
		"ui.common.on": "ON",
		"ui.common.off": "OFF",
		"ui.common.max": "Max",
		"ui.common.purchased": "Purchased",
		"ui.common.in_progress": "In Progress",
		"ui.common.claim": "Claim",
		"ui.common.claimed": "Claimed",
		"ui.common.cancel": "Cancel",
		"ui.common.yes": "Yes",
		"ui.common.no": "No",
		"ui.tab.upgrades": "Upgrades",
		"ui.tab.partners": "Partners",
		"ui.tab.settlement": "Village",
		"ui.tab.prestige": "Prestige",
		"ui.tab.shop": "Shop",
		"ui.progress.boss_time": "Boss Time: {time}s",
		"ui.progress.enemies_count": "Enemies {current} / {required}",
		"ui.progress.hp_bar_value": "{current} / {max}",
		"ui.buy_mode.x1": "x1",
		"ui.buy_mode.x10": "x10",
		"ui.buy_mode.x100": "x100",
		"ui.buy_mode.max": "Max",
		"settings.title": "Settings",
		"settings.language": "Language",
		"settings.language.en": "English",
		"settings.language.ru": "Русский",
		"settings.reset_progress": "Reset Progress",
		"settings.confirm_reset": "Confirm Reset",
		"settings.saved": "Saved",
		"settings.save_failed": "Save failed",
		"settings.progress_reset": "Progress Reset",
		"auto_transition.status_on": "ON",
		"auto_transition.status_off": "OFF",
		"task.in_progress": "In Progress",
		"task.claim": "Claim",
		"task.claimed": "Claimed",
		"task.progress": "{current} / {target} | Reward: {reward}",
		"upgrade.hero.button": "x{count} - {cost}",
		"upgrade.hero.card.name": "Hero",
		"upgrade.hero.card.level_gain": "{level} Lv | +{gain} Damage",
		"upgrade.hero.card.damage": "Damage {damage}",
		"upgrade.hero.card.milestone_next": "x2 at {milestone} Lv",
		"upgrade.hero.card.milestone_max": "Max",
		"upgrade.ability.purchased": "Purchased",
		"upgrade.ability.requires_level": "Requires {level} Lv",
		"upgrade.ability.buy": "Buy: {cost}",
		"upgrade.ability.card.name": "{name}",
		"upgrade.ability.card.rank": "Rank {rank}/{max_rank}",
		"upgrade.ability.unlock_with_duration": "Requires {level} Lv | {duration}",
		"partner.hire_button": "x{count} - {cost}",
		"partner.card.name": "{name}",
		"partner.card.count_gain": "{count} | +{gain} DPS",
		"partner.card.total_dps": "Total {total} DPS",
		"partner.card.milestone_next": "x2 at {milestone} Lv",
		"partner.card.milestone_max": "Max",
		"settlement.requires": "Requires {building}",
		"settlement.build_button": "x{count} - {cost}",
		"settlement.card.name": "{name}",
		"settlement.card.count": "Owned: {count}",
		"settlement.card.milestone_next": "Next milestone: {milestone}",
		"settlement.card.milestone_max": "Max milestones",
		"prestige.action": "Prestige",
		"prestige.action_card.title": "Prestige",
		"prestige.action_card.reward": "Receive +{points}",
		"prestige.action_card.reset_progress": "Reset progress",
		"prestige.action_card.get_points": "get points",
		"prestige.talent_upgrade_bulk": "Upgrade x{count}\n{cost} PP",
		"prestige.card.name": "{name}",
		"prestige.card.count": "Owned: {count}",
		"prestige.card.empty": " ",
		"prestige.confirm.stage_level": "Stage level",
		"prestige.confirm.character_level": "Character level",
		"prestige.confirm.stage_points": "Stage points",
		"prestige.confirm.character_points": "Character points",
		"prestige.confirm.points_to_gain": "Points to gain",
		"prestige.confirm.available_after": "Available after",
		"prestige.confirm.total_earned_after": "Total earned after",
		"prestige.confirm.warning": "All normal progress will reset",
		"prestige.confirm.talents_note": "Purchased prestige talents remain",
		"shop.buy_button": "Buy",
		"zone.01.name": "Hidden Leaf Forest",
		"zone.02.name": "Training Camp",
		"zone.03.name": "Fog Forest",
		"zone.04.name": "Great Naruto Bridge",
		"zone.05.name": "Challenge Forest",
		"zone.06.name": "Challenge Forest",
		"zone.07.name": "Hidden Leaf Forest",
		"zone.08.name": "Hidden Leaf Village",
		"zone.09.name": "Hidden Leaf Village",
		"zone.10.name": "Valley of the End",
		"zone.11.name": "Cave",
		"zone.12.name": "Cave",
		"zone.13.name": "Hidden Leaf Forest",
		"zone.14.name": "Hidden Leaf Forest",
		"zone.15.name": "Hidden Leaf Village",
		"zone.16.name": "Five Kage Hall",
		"zone.17.name": "Shinobi War Field",
		"zone.18.name": "Shinobi War Field",
		"zone.19.name": "Shinobi War Field",
		"zone.20.name": "Shinobi War Field",
		"zone.21.name": "Shinobi War Field",
		"zone.01.boss": "Mizuki",
		"zone.02.boss": "Kakashi Hatake",
		"zone.03.boss": "Haku",
		"zone.04.boss": "Zabuza Momochi",
		"zone.05.boss": "Kabuto Yakushi",
		"zone.06.boss": "Orochimaru",
		"zone.07.boss": "Gaara",
		"zone.08.boss": "Kisame",
		"zone.09.boss": "Itachi Uchiha",
		"zone.10.boss": "Sasuke Uchiha",
		"zone.11.boss": "Sasori",
		"zone.12.boss": "Deidara",
		"zone.13.boss": "Hidan",
		"zone.14.boss": "Kakuzu",
		"zone.15.boss": "Pain",
		"zone.16.boss": "Sasuke Uchiha",
		"zone.17.boss": "Tobi",
		"zone.18.boss": "Madara Uchiha",
		"zone.19.boss": "Madara Jinchuriki",
		"zone.20.boss": "Kaguya Otsutsuki",
		"zone.21.boss": "Sasuke Uchiha",
		"partner.01.name": "Naruto Uzumaki",
		"partner.02.name": "Sasuke Uchiha",
		"partner.03.name": "Sakura Haruno",
		"partner.04.name": "Kakashi Hatake",
		"partner.05.name": "Jiraya",
		"partner.06.name": "Orochimaru",
		"partner.07.name": "Itachi Uchiha",
		"partner.08.name": "Six Path of Pain",
		"partner.09.name": "Konan",
		"partner.10.name": "Tsunade",
		"partner.11.name": "Itachi (Susanoo)",
		"partner.12.name": "Muu",
		"partner.13.name": "Gengetsu Hozuki",
		"partner.14.name": "Killer B",
		"partner.15.name": "Kabuto Yakushi",
		"partner.16.name": "A (4th Raikage)",
		"partner.17.name": "Hiruzen Sarutobi",
		"partner.18.name": "Tobirama Senzu",
		"partner.19.name": "A (3rd Raikage)",
		"partner.20.name": "Hashirama Senzu",
		"partner.21.name": "Obito Uchiha",
		"partner.22.name": "Madara Uchiha",
		"partner.23.name": "Minato Namikaze",
		"partner.24.name": "Maito Guy",
		"partner.25.name": "Obito Jinchuriki",
		"partner.26.name": "Madara Jinchuriki",
		"partner.27.name": "Sasuke Six Paths",
		"partner.28.name": "Naruto Six Paths",
		"building.01.name": "Training Ground",
		"building.02.name": "Ichiraku Ramen",
		"building.03.name": "Knight Hut",
		"building.04.name": "War Banner",
		"building.05.name": "Clock Tower",
		"building.06.name": "Boss Shrine",
		"building.01.purchase_gain": "+{bonus}% Partner DPS from purchase",
		"building.01.total_bonus": "Total Partner DPS bonus: +{bonus}%",
		"building.02.purchase_gain": "+{bonus}% Gold gain from purchase",
		"building.02.total_bonus": "Total Gold gain bonus: +{bonus}%",
		"building.03.purchase_gain": "+{bonus}% Click damage from purchase",
		"building.03.total_bonus": "Total Click damage bonus: +{bonus}%",
		"building.04.purchase_gain": "+{bonus}% Ability duration from purchase",
		"building.04.total_bonus": "Total Ability duration bonus: +{bonus}%",
		"building.05.purchase_gain": "+{bonus}% Cooldown reduction from purchase",
		"building.05.total_bonus": "Total Cooldown reduction: +{bonus}%",
		"building.06.purchase_gain": "+{bonus}% Boss Gold from purchase",
		"building.06.total_bonus": "Total Boss Gold bonus: +{bonus}%",
		"prestige.talent.01.name": "Focus Training",
		"prestige.talent.02.name": "Trade Routes",
		"prestige.talent.03.name": "Command Aura",
		"prestige.talent.04.name": "Quick Hands",
		"prestige.talent.05.name": "Builder Wisdom",
		"prestige.talent.06.name": "Boss Hunter",
		"prestige.talent.01.purchase_gain": "+{bonus}% Click damage from purchase",
		"prestige.talent.01.total_bonus": "Total Click damage bonus: +{bonus}%",
		"prestige.talent.02.purchase_gain": "+{bonus}% Gold gain from purchase",
		"prestige.talent.02.total_bonus": "Total Gold gain bonus: +{bonus}%",
		"prestige.talent.03.purchase_gain": "+{bonus}% Partner DPS from purchase",
		"prestige.talent.03.total_bonus": "Total Partner DPS bonus: +{bonus}%",
		"prestige.talent.04.purchase_gain": "+{bonus}% Autoclick speed from purchase",
		"prestige.talent.04.total_bonus": "Total Autoclick speed bonus: +{bonus}%",
		"prestige.talent.05.purchase_gain": "+{bonus}% Settlement effectiveness from purchase",
		"prestige.talent.05.total_bonus": "Total Settlement effectiveness bonus: +{bonus}%",
		"prestige.talent.06.purchase_gain": "+{bonus}% Boss damage from purchase",
		"prestige.talent.06.total_bonus": "Total Boss damage bonus: +{bonus}%",
		"shop.gold_pack_small.name": "Small Gold Pack",
		"shop.gold_pack_small.description": "Gain stage-scaled gold",
		"shop.gold_pack_large.name": "Large Gold Pack",
		"shop.gold_pack_large.description": "Gain a large stage-scaled gold reward",
		"shop.boss_retry_token.name": "Boss Retry",
		"shop.boss_retry_token.description": "Return to the failed boss level",
		"shop.task_boost.name": "Task Reward Boost",
		"shop.task_boost.description": "Next claimed task gives x2 gold",
		"task.manual_damage_500.title": "Deal 500 manual damage",
		"task.defeat_25_enemies.title": "Defeat 25 enemies",
		"task.defeat_2_elites.title": "Defeat 2 elite enemies",
		"task.defeat_1_boss.title": "Defeat 1 boss",
		"task.gain_10_hero_levels.title": "Gain 10 Hero Levels",
		"task.hire_10_partners.title": "Hire 10 partners",
		"task.build_5_buildings.title": "Build 5 settlement buildings",
		"task.activate_autoclick_1.title": "Activate Autoclick 1 time",
		"task.gain_10_game_levels.title": "Reach 10 more levels",
		"ability.autoclick.name": "Autoclick",
		"ability.gold_bonus.name": "Gold Bonus",
		"ability.focus_burst.name": "Focus Burst",
		"ability.rally.name": "Rally",
		"ability.autoclick.effect": "Autoclick attacks {hits}/s",
		"ability.gold_bonus.effect": "Gold gain x{multiplier}",
		"ability.focus_burst.effect": "Click damage x{multiplier}",
		"ability.rally.effect": "Partner DPS x{multiplier}",
		"ability.autoclick.duration": "Duration: {seconds}s",
		"ability.gold_bonus.duration": "Duration: {seconds}s",
		"ability.focus_burst.duration": "Duration: {seconds}s",
		"ability.rally.duration": "Duration: {seconds}s",
		"enemy.pool_01.enemy_01.name": "Naruto Uzumaki",
		"enemy.pool_01.enemy_02.name": "Sasuke Uchiha",
		"enemy.pool_01.enemy_03.name": "Sakura Haruno",
		"enemy.pool_01.enemy_04.name": "Rock Lee",
		"enemy.pool_01.enemy_05.name": "Neji Hyuga",
		"enemy.pool_01.enemy_06.name": "Ten-Ten",
		"enemy.pool_01.enemy_07.name": "Hinata Hyuga",
		"enemy.pool_01.enemy_08.name": "Kiba Inuzuka",
		"enemy.pool_01.enemy_09.name": "Shino Aburame",
		"enemy.pool_01.enemy_10.name": "Kankuro",
		"enemy.pool_01.enemy_11.name": "Temari",
		"enemy.pool_01.enemy_12.name": "Jirono",
		"enemy.pool_01.enemy_13.name": "Kidomaru",
		"enemy.pool_01.enemy_14.name": "Tauy",
		"enemy.pool_01.enemy_15.name": "Sakon and Ukon",
		"enemy.pool_01.elite_01.name": "Iruka Umino",
		"enemy.pool_01.elite_02.name": "Maito Guy",
		"enemy.pool_01.elite_03.name": "Kurenai Uhi",
		"enemy.pool_01.elite_04.name": "Baki",
		"enemy.pool_11.enemy_01.name": "Jugo",
		"enemy.pool_11.enemy_02.name": "Karin",
		"enemy.pool_11.enemy_03.name": "Suigetsu Hozuki",
		"enemy.pool_11.enemy_04.name": "Ino Yamanaka",
		"enemy.pool_11.enemy_05.name": "Shikamaru Nara",
		"enemy.pool_11.enemy_06.name": "Choji Akimichi",
		"enemy.pool_11.enemy_07.name": "Sai",
		"enemy.pool_11.enemy_08.name": "Sakura Haruno",
		"enemy.pool_11.enemy_09.name": "Naruto Uzumaki",
		"enemy.pool_11.enemy_10.name": "Sasuke Uchiha",
		"enemy.pool_11.enemy_11.name": "Yamato",
		"enemy.pool_11.enemy_12.name": "Konan",
		"enemy.pool_11.enemy_13.name": "Karui",
		"enemy.pool_11.enemy_14.name": "Darui",
		"enemy.pool_11.enemy_15.name": "Omoi",
		"enemy.pool_11.elite_01.name": "Asuma Sarutobi",
		"enemy.pool_11.elite_02.name": "Jiraya",
		"enemy.pool_11.elite_03.name": "Tsunade",
		"enemy.pool_11.elite_04.name": "Orochimaru",
		"enemy.pool_11.elite_05.name": "Itachi Uchiha",
		"enemy.pool_17.enemy_01.name": "Muu",
		"enemy.pool_17.enemy_02.name": "Oonoki",
		"enemy.pool_17.enemy_03.name": "Gengetsu Hozuki",
		"enemy.pool_17.enemy_04.name": "Mei Terumi",
		"enemy.pool_17.enemy_05.name": "Tobirama Senzu",
		"enemy.pool_17.enemy_06.name": "Hiruzen Sarutobi",
		"enemy.pool_17.enemy_07.name": "Killer B",
		"enemy.pool_17.enemy_08.name": "A (Third Raikage)",
		"enemy.pool_17.enemy_09.name": "A (Fourth Raikage)",
		"enemy.pool_17.elite_01.name": "Minato Namikaze",
		"enemy.pool_17.elite_02.name": "Hashirama Senzu",
		"enemy.pool_17.elite_03.name": "Maito Guy (8 Gates)",
		"ui.combat.gold_reward": "+{amount} gold",
	},
	"ru": {
		"ui.common.close": "Закрыть",
		"ui.common.buy": "Купить",
		"ui.common.cost": "Цена",
		"ui.common.reward": "Награда",
		"ui.common.level": "Уровень",
		"ui.common.cleared": "Пройдено",
		"ui.common.on": "Вкл",
		"ui.common.off": "Выкл",
		"ui.common.max": "Макс",
		"ui.common.purchased": "Куплено",
		"ui.common.in_progress": "В Процессе",
		"ui.common.claim": "Получить",
		"ui.common.claimed": "Получено",
		"ui.common.cancel": "Отмена",
		"ui.common.yes": "Да",
		"ui.common.no": "Нет",
		"ui.tab.upgrades": "Улучшения",
		"ui.tab.partners": "Команда",
		"ui.tab.settlement": "Деревня",
		"ui.tab.prestige": "Престиж",
		"ui.tab.shop": "Магазин",
		"ui.progress.boss_time": "Таймер Босса: {time}с",
		"ui.progress.enemies_count": "Врагов {current} / {required}",
		"ui.progress.hp_bar_value": "{current} / {max}",
		"ui.buy_mode.x1": "x1",
		"ui.buy_mode.x10": "x10",
		"ui.buy_mode.x100": "x100",
		"ui.buy_mode.max": "Макс",
		"settings.title": "Настройки",
		"settings.language": "Язык",
		"settings.language.en": "English",
		"settings.language.ru": "Русский",
		"settings.reset_progress": "Сбросить Прогресс",
		"settings.confirm_reset": "Подтвердить Сброс",
		"settings.saved": "Сохранено",
		"settings.save_failed": "Ошибка Сохранения",
		"settings.progress_reset": "Сброс Прогресса",
		"auto_transition.status_on": "Вкл",
		"auto_transition.status_off": "Выкл",
		"task.in_progress": "В Процессе",
		"task.claim": "Получить",
		"task.claimed": "Получено",
		"task.progress": "{current} / {target} | Награда: {reward}",
		"upgrade.hero.button": "x{count} - {cost}",
		"upgrade.hero.card.name": "Герой",
		"upgrade.hero.card.level_gain": "{level} Ур | +{gain} Урон",
		"upgrade.hero.card.damage": "Урон {damage}",
		"upgrade.hero.card.milestone_next": "x2 на {milestone} Ур",
		"upgrade.hero.card.milestone_max": "Максимум",
		"upgrade.ability.purchased": "Куплено",
		"upgrade.ability.requires_level": "Требуется {level} Ур",
		"upgrade.ability.buy": "Купить: {cost}",
		"upgrade.ability.card.name": "{name}",
		"upgrade.ability.card.rank": "Ранг {rank}/{max_rank}",
		"upgrade.ability.unlock_with_duration": "Требуется {level} Ур | {duration}",
		"partner.hire_button": "x{count} - {cost}",
		"partner.card.name": "{name}",
		"partner.card.count_gain": "{count} | +{gain} Урон",
		"partner.card.total_dps": "Всего {total} DPS",
		"partner.card.milestone_next": "x2 на {milestone} Ур",
		"partner.card.milestone_max": "Максимум",
		"settlement.requires": "Требуется {building}",
		"settlement.build_button": "x{count} - {cost}",
		"settlement.card.name": "{name}",
		"settlement.card.count": "Кол-во: {count}",
		"settlement.card.milestone_next": "Следующий milestone: {milestone}",
		"settlement.card.milestone_max": "Максимальный milestone",
		"prestige.action": "Престиж",
		"prestige.action_card.title": "Престиж",
		"prestige.action_card.reward": "Получить +{points}",
		"prestige.action_card.reset_progress": "Сбросить прогресс",
		"prestige.action_card.get_points": "получить очки",
		"prestige.talent_upgrade_bulk": "Улучшить x{count}\n{cost} ОП",
		"prestige.card.name": "{name}",
		"prestige.card.count": "Кол-во: {count}",
		"prestige.card.empty": " ",
		"prestige.confirm.stage_level": "Этап",
		"prestige.confirm.character_level": "Уровень",
		"prestige.confirm.stage_points": "Очки этапа",
		"prestige.confirm.character_points": "Очки уровня",
		"prestige.confirm.points_to_gain": "Очки к получению",
		"prestige.confirm.available_after": "Доступно после",
		"prestige.confirm.total_earned_after": "Все заработано",
		"prestige.confirm.warning": "Весь прогресс будет сброшен",
		"prestige.confirm.talents_note": "Купленные таланты престижа сохраняются",
		"shop.buy_button": "Купить",
		"zone.01.name": "Лес Скрытого Листа",
		"zone.02.name": "Тренировочная Площадка",
		"zone.03.name": "Лес Тумана",
		"zone.04.name": "Великий мост Наруто",
		"zone.05.name": "Лес Испытаний",
		"zone.06.name": "Лес Испытаний",
		"zone.07.name": "Лес Скрытого Листа",
		"zone.08.name": "Деревня Скрытого Листа",
		"zone.09.name": "Деревня Скрытого Листа",
		"zone.10.name": "Долина Завершения",
		"zone.11.name": "Пещера",
		"zone.12.name": "Пещера",
		"zone.13.name": "Лес Скрытого Листа",
		"zone.14.name": "Лес Скрытого Листа",
		"zone.15.name": "Деревня Скрытого Листа",
		"zone.16.name": "Зал Пяти Каге",
		"zone.17.name": "Поле Войны Шиноби",
		"zone.18.name": "Поле Войны Шиноби",
		"zone.19.name": "Поле Войны Шиноби",
		"zone.20.name": "Поле Войны Шиноби",
		"zone.21.name": "Поле Войны Шиноби",
		"zone.01.boss": "Мизуки",
		"zone.02.boss": "Какаши Хатаке",
		"zone.03.boss": "Хаку",
		"zone.04.boss": "Забуза Момочи",
		"zone.05.boss": "Кабуто Якуши",
		"zone.06.boss": "Орочимару",
		"zone.07.boss": "Гаара",
		"zone.08.boss": "Кисаме",
		"zone.09.boss": "Итачи Учиха",
		"zone.10.boss": "Саске Учиха",
		"zone.11.boss": "Сасори",
		"zone.12.boss": "Дейдара",
		"zone.13.boss": "Хидан",
		"zone.14.boss": "Какузу",
		"zone.15.boss": "Пейн",
		"zone.16.boss": "Саске Учиха",
		"zone.17.boss": "Тоби",
		"zone.18.boss": "Мадара Учиха",
		"zone.19.boss": "Мадара Джинчурики",
		"zone.20.boss": "Кагуя Ооцуцуки",
		"zone.21.boss": "Саске Учиха",
		"partner.01.name": "Наруто Узумаки",
		"partner.02.name": "Саске Учиха",
		"partner.03.name": "Сакура Харуно",
		"partner.04.name": "Какаши Хатаке",
		"partner.05.name": "Джирайя",
		"partner.06.name": "Орочимару",
		"partner.07.name": "Итачи Учиха",
		"partner.08.name": "Шесть Путей Пейна",
		"partner.09.name": "Конан",
		"partner.10.name": "Цунаде",
		"partner.11.name": "Итачи (Сусаноо)",
		"partner.12.name": "Муу",
		"partner.13.name": "Генгецу Хозуки",
		"partner.14.name": "Киллер Би",
		"partner.15.name": "Кабуто Якуши",
		"partner.16.name": "Эй (4ый Райкаге)",
		"partner.17.name": "Хирузен Сарутоби",
		"partner.18.name": "Тобирама Сенджу",
		"partner.19.name": "Эй (3ий Райкаге)",
		"partner.20.name": "Хаширама Сенджу",
		"partner.21.name": "Обито Учиха",
		"partner.22.name": "Мадара Учиха",
		"partner.23.name": "Минато Намикадзе",
		"partner.24.name": "Майто Гай",
		"partner.25.name": "Обито Джинчурики",
		"partner.26.name": "Мадара Джинчурики",
		"partner.27.name": "Саске Шесть Путей",
		"partner.28.name": "Наруто Шесть Путей",
		"building.01.name": "Тренировочное Поле",
		"building.02.name": "Ичираку Рамен",
		"building.03.name": "Дом шиноби",
		"building.04.name": "Боевой стяг",
		"building.05.name": "Часовая башня",
		"building.06.name": "Святилище босса",
		"building.01.purchase_gain": "+{bonus}% к ДПС партнёров за покупку",
		"building.01.total_bonus": "Текущий бонус к ДПС партнёров: +{bonus}%",
		"building.02.purchase_gain": "+{bonus}% к получаемому золоту за покупку",
		"building.02.total_bonus": "Текущий бонус к получаемому золоту: +{bonus}%",
		"building.03.purchase_gain": "+{bonus}% к урону клика за покупку",
		"building.03.total_bonus": "Текущий бонус к урону клика: +{bonus}%",
		"building.04.purchase_gain": "+{bonus}% к длительности способностей за покупку",
		"building.04.total_bonus": "Текущий бонус к длительности способностей: +{bonus}%",
		"building.05.purchase_gain": "+{bonus}% к сокращению перезарядки за покупку",
		"building.05.total_bonus": "Текущее сокращение перезарядки: +{bonus}%",
		"building.06.purchase_gain": "+{bonus}% к золоту с боссов за покупку",
		"building.06.total_bonus": "Текущий бонус к золоту с боссов: +{bonus}%",
		"prestige.talent.01.name": "Тренировка фокуса",
		"prestige.talent.02.name": "Торговые пути",
		"prestige.talent.03.name": "Аура командира",
		"prestige.talent.04.name": "Быстрые руки",
		"prestige.talent.05.name": "Мудрость строителя",
		"prestige.talent.06.name": "Охотник на боссов",
		"prestige.talent.01.purchase_gain": "+{bonus}% к урону клика за покупку",
		"prestige.talent.01.total_bonus": "Текущий бонус к урону клика: +{bonus}%",
		"prestige.talent.02.purchase_gain": "+{bonus}% к получаемому золоту за покупку",
		"prestige.talent.02.total_bonus": "Текущий бонус к получаемому золоту: +{bonus}%",
		"prestige.talent.03.purchase_gain": "+{bonus}% к ДПС партнёров за покупку",
		"prestige.talent.03.total_bonus": "Текущий бонус к ДПС партнёров: +{bonus}%",
		"prestige.talent.04.purchase_gain": "+{bonus}% к скорости автоклика за покупку",
		"prestige.talent.04.total_bonus": "Текущий бонус к скорости автоклика: +{bonus}%",
		"prestige.talent.05.purchase_gain": "+{bonus}% к эффективности поселения за покупку",
		"prestige.talent.05.total_bonus": "Текущий бонус к эффективности поселения: +{bonus}%",
		"prestige.talent.06.purchase_gain": "+{bonus}% к урону по боссам за покупку",
		"prestige.talent.06.total_bonus": "Текущий бонус к урону по боссам: +{bonus}%",
		"shop.gold_pack_small.name": "",
		"shop.gold_pack_small.description": "",
		"shop.gold_pack_large.name": "",
		"shop.gold_pack_large.description": "",
		"shop.boss_retry_token.name": "",
		"shop.boss_retry_token.description": "",
		"shop.task_boost.name": "",
		"shop.task_boost.description": "",
		"task.manual_damage_500.title": "",
		"task.defeat_25_enemies.title": "",
		"task.defeat_2_elites.title": "",
		"task.defeat_1_boss.title": "",
		"task.gain_10_hero_levels.title": "",
		"task.hire_10_partners.title": "",
		"task.build_5_buildings.title": "",
		"task.activate_autoclick_1.title": "",
		"task.gain_10_game_levels.title": "",
		"ability.autoclick.name": "Автоклик",
		"ability.gold_bonus.name": "Бонус золота",
		"ability.focus_burst.name": "Фокус силы",
		"ability.rally.name": "Боевой клич",
		"ability.autoclick.effect": "Автоклик атакует {hits}/с",
		"ability.gold_bonus.effect": "Получение золота x{multiplier}",
		"ability.focus_burst.effect": "Урон клика x{multiplier}",
		"ability.rally.effect": "ДПС партнёров x{multiplier}",
		"ability.autoclick.duration": "Длительность: {seconds}с",
		"ability.gold_bonus.duration": "Длительность: {seconds}с",
		"ability.focus_burst.duration": "Длительность: {seconds}с",
		"ability.rally.duration": "Длительность: {seconds}с",
		"enemy.pool_01.enemy_01.name": "Наруто Узумаки",
		"enemy.pool_01.enemy_02.name": "Саске Учиха",
		"enemy.pool_01.enemy_03.name": "Сакура Харуно",
		"enemy.pool_01.enemy_04.name": "Рок Ли",
		"enemy.pool_01.enemy_05.name": "Неджи Хьюга",
		"enemy.pool_01.enemy_06.name": "Тен-Тен",
		"enemy.pool_01.enemy_07.name": "Хината Хьюга",
		"enemy.pool_01.enemy_08.name": "Киба Инузука",
		"enemy.pool_01.enemy_09.name": "Шино Абураме",
		"enemy.pool_01.enemy_10.name": "Канкуро",
		"enemy.pool_01.enemy_11.name": "Темари",
		"enemy.pool_01.enemy_12.name": "Джиробо",
		"enemy.pool_01.enemy_13.name": "Кидомару",
		"enemy.pool_01.enemy_14.name": "Таюи",
		"enemy.pool_01.enemy_15.name": "Сакон и Укон",
		"enemy.pool_01.elite_01.name": "Ирука Умино",
		"enemy.pool_01.elite_02.name": "Майто Гай",
		"enemy.pool_01.elite_03.name": "Куренай Юхи",
		"enemy.pool_01.elite_04.name": "Баки",
		"enemy.pool_11.enemy_01.name": "Джуго",
		"enemy.pool_11.enemy_02.name": "Карин",
		"enemy.pool_11.enemy_03.name": "Суйгетцу Хозуки",
		"enemy.pool_11.enemy_04.name": "Ино Яманака",
		"enemy.pool_11.enemy_05.name": "Шикамару Нара",
		"enemy.pool_11.enemy_06.name": "Чоджи Акимичи",
		"enemy.pool_11.enemy_07.name": "Сай",
		"enemy.pool_11.enemy_08.name": "Сакура Харуно",
		"enemy.pool_11.enemy_09.name": "Наруто Узумаки",
		"enemy.pool_11.enemy_10.name": "Саске Учиха",
		"enemy.pool_11.enemy_11.name": "Ямато",
		"enemy.pool_11.enemy_12.name": "Конан",
		"enemy.pool_11.enemy_13.name": "Каруи",
		"enemy.pool_11.enemy_14.name": "Даруи",
		"enemy.pool_11.enemy_15.name": "Омои",
		"enemy.pool_11.elite_01.name": "Асума Сарутоби",
		"enemy.pool_11.elite_02.name": "Джирая",
		"enemy.pool_11.elite_03.name": "Цунаде",
		"enemy.pool_11.elite_04.name": "Орочимару",
		"enemy.pool_11.elite_05.name": "Итачи Учиха",
		"enemy.pool_17.enemy_01.name": "Муу",
		"enemy.pool_17.enemy_02.name": "Ооноки",
		"enemy.pool_17.enemy_03.name": "Генгецу Хозуки",
		"enemy.pool_17.enemy_04.name": "Мей Теруми",
		"enemy.pool_17.enemy_05.name": "Тобирама Сенджу",
		"enemy.pool_17.enemy_06.name": "Хирузен Сарутоби",
		"enemy.pool_17.enemy_07.name": "Киллер Би",
		"enemy.pool_17.enemy_08.name": "Эй (Третий Райкаге)",
		"enemy.pool_17.enemy_09.name": "Эй (Четвертый Райкаге)",
		"enemy.pool_17.elite_01.name": "Минато Намикадзе",
		"enemy.pool_17.elite_02.name": "Хаширама Сенджу",
		"enemy.pool_17.elite_03.name": "Майто Гай (8 Врат)",
		"ui.combat.gold_reward": "+{amount} золота",
	},
}


static func get_translations() -> Dictionary:
	return TRANSLATIONS.duplicate(true)
