class_name LocalizationData
extends RefCounted

# AUTO-GENERATED — do not edit by hand.
# Source: res://localization/game_text.csv
# Regenerate with: godot --headless --script res://scripts/tools/GenerateLocalizationData.gd
# Generated key count: 369
# Generated at: 1781436642

const TRANSLATIONS: Dictionary = {
	"en": {
		"ui.common.close": "Close",
		"ui.common.buy": "Buy",
		"ui.common.cost": "Cost",
		"ui.common.reward": "Reward",
		"ui.common.level": "Level",
		"ui.common.cleared": "Cleared",
		"ui.common.on": "ON",
		"ui.common.off": "OFF",
		"ui.common.max": "Max",
		"ui.common.purchased": "Purchased",
		"ui.common.in_progress": "In Progress",
		"ui.common.claim": "Claim",
		"ui.common.claimed": "Claimed",
		"ui.common.cancel": "Cancel",
		"ui.common.yes": "Yes",
		"ui.common.no": "No",
		"ui.tab.upgrades": "Upgrades",
		"ui.tab.partners": "Partners",
		"ui.tab.settlement": "Village",
		"ui.tab.prestige": "Prestige",
		"ui.tab.shop": "Shop",
		"ui.progress.boss_time": "Boss Time: {time}s",
		"ui.progress.enemies_count": "Enemies {current} / {required}",
		"ui.progress.hp_bar_value": "{current} / {max}",
		"ui.buy_mode.x1": "x1",
		"ui.buy_mode.x10": "x10",
		"ui.buy_mode.x100": "x100",
		"ui.buy_mode.max": "Max",
		"settings.title": "Settings",
		"settings.language": "Language",
		"settings.language.en": "English",
		"settings.language.ru": "Русский",
		"settings.reset_progress": "Reset Progress",
		"settings.confirm_reset": "Confirm Reset",
		"settings.saved": "Saved",
		"settings.save_failed": "Save failed",
		"settings.progress_reset": "Progress Reset",
		"auto_transition.status_on": "ON",
		"auto_transition.status_off": "OFF",
		"auto_transition.description.line_1": "When enabled cleared",
		"auto_transition.description.line_2": "stages automatically",
		"auto_transition.description.line_3": "move to the next",
		"auto_transition.description.line_4": "unlocked level",
		"skill_popup.hero.title": "Skill",
		"skill_popup.partner.title": "Partner Skill",
		"skill_popup.requirement.hero_level": "Requires {level} Lv",
		"skill_popup.requirement.ability_purchase": "Requires {ability}",
		"skill_popup.requirement.partner_count": "Requires {count}",
		"skill_popup.current.hero_level": "Current: {current} / {required}",
		"skill_popup.current.partner_count": "Current: {current} / {required}",
		"skill_popup.current.unlocked": "Unlocked",
		"skill_popup.button.buy": "Buy: {cost}",
		"skill_popup.button.locked": "Locked",
		"skill_popup.button.purchased": "Purchased",
		"task.in_progress": "In Progress",
		"task.claim": "Claim",
		"task.claimed": "Claimed",
		"task.progress": "{current} / {target}",
		"task.reward": "Reward: {reward} Gold",
		"upgrade.hero.button": "x{count} - {cost}",
		"upgrade.hero.card.name": "Hero",
		"upgrade.hero.card.level_gain": "{level} Lv | +{gain} Damage",
		"upgrade.hero.card.damage": "Damage {damage}",
		"upgrade.hero.card.milestone_next": "x2 at {milestone} Lv",
		"upgrade.hero.card.milestone_max": "Max",
		"upgrade.ability.purchased": "Purchased",
		"upgrade.ability.requires_level": "Requires {level} Lv",
		"upgrade.ability.buy": "Buy: {cost}",
		"upgrade.ability.card.name": "{name}",
		"upgrade.ability.card.rank": "Rank {rank}/{max_rank}",
		"upgrade.ability.unlock_with_duration": "{duration}",
		"partner.hire_button": "x{count} - {cost}",
		"partner.card.name": "{name}",
		"partner.card.count_gain": "{count} | +{gain} DPS",
		"partner.card.total_dps": "Total {total} DPS",
		"partner.card.milestone_next": "x2 at {milestone} Lv",
		"partner.card.milestone_max": "Max",
		"settlement.build_button": "x{count} - {cost}",
		"settlement.card.name": "{name}",
		"settlement.card.count": "Owned: {count}",
		"settlement.card.milestone_next": "x2 at {milestone} Lv",
		"settlement.card.milestone_max": "Max",
		"prestige.action": "Prestige",
		"prestige.action_card.title": "Prestige",
		"prestige.action_card.reward": "Receive +{points}",
		"prestige.action_card.reset_progress": "Reset progress",
		"prestige.action_card.get_points": "Get points",
		"prestige.talent_upgrade_bulk": "x{count} - {cost}",
		"prestige.card.name": "{name}",
		"prestige.card.count": "Owned: {count}",
		"prestige.card.empty": " ",
		"prestige.confirm.stage_level": "Stage",
		"prestige.confirm.character_level": "Level",
		"prestige.confirm.stage_points": "Stage points",
		"prestige.confirm.character_points": "Level points",
		"prestige.confirm.points_to_gain": "Points to gain: {points}",
		"prestige.confirm.available_after": "Available after",
		"prestige.confirm.total_earned_after": "Total earned after",
		"prestige.confirm.warning": "All normal progress will reset",
		"prestige.confirm.talents_note": "Purchased talents remain",
		"prestige.confirm.title": "Prestige",
		"prestige.confirm.stage": "Stage: {stage}",
		"prestige.confirm.level": "Level: {level}",
		"prestige.confirm.reset_warning": "All progress will be reset",
		"prestige.confirm.talents_kept": "Prestige talents are kept",
		"prestige.confirm.yes": "Yes",
		"prestige.confirm.no": "No",
		"shop.buy_button": "Buy",
		"shop.confirm.title": "Confirm purchase",
		"shop.confirm.confirm": "Confirm",
		"shop.confirm.cancel": "Cancel",
		"zone.01.name": "Hidden Leaf Forest",
		"zone.02.name": "Training Camp",
		"zone.03.name": "Fog Forest",
		"zone.04.name": "Great Naruto Bridge",
		"zone.05.name": "Challenge Forest",
		"zone.06.name": "Challenge Forest",
		"zone.07.name": "Hidden Leaf Forest",
		"zone.08.name": "Hidden Leaf Village",
		"zone.09.name": "Hidden Leaf Village",
		"zone.10.name": "Valley of the End",
		"zone.11.name": "Cave",
		"zone.12.name": "Cave",
		"zone.13.name": "Hidden Leaf Forest",
		"zone.14.name": "Hidden Leaf Forest",
		"zone.15.name": "Hidden Leaf Village",
		"zone.16.name": "Five Kage Hall",
		"zone.17.name": "Shinobi War Field",
		"zone.18.name": "Shinobi War Field",
		"zone.19.name": "Shinobi War Field",
		"zone.20.name": "Shinobi War Field",
		"zone.21.name": "Shinobi War Field",
		"zone.01.boss": "Mizuki",
		"zone.02.boss": "Kakashi Hatake",
		"zone.03.boss": "Haku",
		"zone.04.boss": "Zabuza Momochi",
		"zone.05.boss": "Kabuto Yakushi",
		"zone.06.boss": "Orochimaru",
		"zone.07.boss": "Gaara",
		"zone.08.boss": "Kisame",
		"zone.09.boss": "Itachi Uchiha",
		"zone.10.boss": "Sasuke Uchiha",
		"zone.11.boss": "Sasori",
		"zone.12.boss": "Deidara",
		"zone.13.boss": "Hidan",
		"zone.14.boss": "Kakuzu",
		"zone.15.boss": "Pain",
		"zone.16.boss": "Sasuke Uchiha",
		"zone.17.boss": "Tobi",
		"zone.18.boss": "Madara Uchiha",
		"zone.19.boss": "Madara Jinchuriki",
		"zone.20.boss": "Kaguya Otsutsuki",
		"zone.21.boss": "Sasuke Uchiha",
		"partner.01.name": "Naruto Uzumaki",
		"partner.02.name": "Sasuke Uchiha",
		"partner.03.name": "Sakura Haruno",
		"partner.04.name": "Kakashi Hatake",
		"partner.05.name": "Jiraya",
		"partner.06.name": "Orochimaru",
		"partner.07.name": "Itachi Uchiha",
		"partner.08.name": "Six Path of Pain",
		"partner.09.name": "Konan",
		"partner.10.name": "Tsunade",
		"partner.11.name": "Itachi (Susanoo)",
		"partner.12.name": "Muu",
		"partner.13.name": "Gengetsu Hozuki",
		"partner.14.name": "Killer B",
		"partner.15.name": "Kabuto Yakushi",
		"partner.16.name": "A (4th Raikage)",
		"partner.17.name": "Hiruzen Sarutobi",
		"partner.18.name": "Tobirama Senzu",
		"partner.19.name": "A (3rd Raikage)",
		"partner.20.name": "Hashirama Senzu",
		"partner.21.name": "Obito Uchiha",
		"partner.22.name": "Madara Uchiha",
		"partner.23.name": "Minato Namikaze",
		"partner.24.name": "Maito Guy",
		"partner.25.name": "Obito Jinchuriki",
		"partner.26.name": "Madara Jinchuriki",
		"partner.27.name": "Sasuke Six Paths",
		"partner.28.name": "Naruto Six Paths",
		"building.01.name": "Training Ground",
		"building.02.name": "Hokage Residence",
		"building.03.name": "Ichiraku Ramen",
		"building.04.name": "Hospital",
		"building.05.name": "Shinobi Academy",
		"building.06.name": "Hokage Rock",
		"building.01.purchase_gain": "+{bonus}% DPS",
		"building.01.total_bonus": "DPS +{bonus}%",
		"building.02.purchase_gain": "+{bonus}% Gold",
		"building.02.total_bonus": "Gold +{bonus}%",
		"building.03.purchase_gain": "+{bonus}% Damage",
		"building.03.total_bonus": "Damage +{bonus}%",
		"building.04.purchase_gain": "+{bonus}% Ability",
		"building.04.total_bonus": "Ability +{bonus}%",
		"building.05.purchase_gain": "-{bonus}% CD",
		"building.05.total_bonus": "CD -{bonus}%",
		"building.06.purchase_gain": "+{bonus}% Boss Gold",
		"building.06.total_bonus": "Boss Gold +{bonus}%",
		"prestige.talent.01.name": "Empower",
		"prestige.talent.02.name": "Bounty Hunter",
		"prestige.talent.03.name": "Warchief",
		"prestige.talent.04.name": "Quick Hands",
		"prestige.talent.05.name": "Builder",
		"prestige.talent.06.name": "Boss Hunter",
		"prestige.talent.01.purchase_gain": "+{bonus}% Damage",
		"prestige.talent.01.total_bonus": "Damage +{bonus}%",
		"prestige.talent.02.purchase_gain": "+{bonus}% Gold",
		"prestige.talent.02.total_bonus": "Gold +{bonus}%",
		"prestige.talent.03.purchase_gain": "+{bonus}% DPS",
		"prestige.talent.03.total_bonus": "DPS +{bonus}%",
		"prestige.talent.04.purchase_gain": "+{bonus}% Autoclick",
		"prestige.talent.04.total_bonus": "Autoclick +{bonus}%",
		"prestige.talent.05.purchase_gain": "+{bonus}% Settlement",
		"prestige.talent.05.total_bonus": "Settlement +{bonus}%",
		"prestige.talent.06.purchase_gain": "+{bonus}% Boss Damage",
		"prestige.talent.06.total_bonus": "Boss Damage +{bonus}%",
		"shop.gold_pack_small.name": "Small Gold Pack",
		"shop.gold_pack_small.description": "Gain 5 hours of gold",
		"shop.gold_pack_large.name": "Large Gold Pack",
		"shop.gold_pack_large.description": "Gain 24 hours of gold",
		"shop.boss_retry_token.name": "Boss Retry",
		"shop.boss_retry_token.description": "Return to the failed boss level",
		"shop.task_boost.name": "Task Reward Boost",
		"shop.task_boost.description": "Next claimed task gives x2 gold",
		"shop.permanent_partner_dps_x2.name": "Permanent DPS x2",
		"shop.permanent_partner_dps_x2.description": "Permanently х2 DPS",
		"shop.permanent_click_damage_x2.name": "Permanent Damage x2",
		"shop.permanent_click_damage_x2.description": "Permanently х2 Damage",
		"shop.permanent_gold_x2.name": "Permanent Gold x2",
		"shop.permanent_gold_x2.description": "Permanently x2 Gold",
		"shop.buy_button_count": "x{count} - {cost}",
		"shop.card.gold_reward": "Gives +{amount} Gold",
		"shop.card.partner_dps_multiplier": "Gives DPS x{multiplier}",
		"shop.card.click_damage_multiplier": "Gives Damage x{multiplier}",
		"shop.card.gold_multiplier": "Gives Gold x{multiplier}",
		"shop.card.owned": "Owned: {count}",
		"shop.card.total_multiplier": "Bonus: x{multiplier}",
		"shop.rewarded_gems_ad.name": "Watch Ad: +3 Gems",
		"shop.rewarded_gems_ad.description": "Gems for AD",
		"shop.card.rewarded_gems": "+{amount} Gems",
		"shop.button.watch_ad": "Watch Ad",
		"shop.button.open": "Open",
		"shop.gem_purchase_entry.name": "Buy Gems",
		"shop.gem_purchase_entry.description": "Purchase gems",
		"shop.card.gem_purchase_entry": "Buy Gems",
		"shop.gem_purchase.title": "Buy Gems",
		"shop.gem_purchase.invalid_product": "Invalid gem product",
		"shop.gem_purchase.success": "+{amount} Gems!",
		"shop.gem_purchase.cancelled": "Purchase cancelled",
		"shop.gem_purchase.error": "Purchase failed",
		"shop.gem_purchase.buy": "Buy",
		"shop.gem_purchase.amount_plain": "+{amount} Gems",
		"shop.gem_purchase.amount_bonus": "+{base} Gems +{bonus} Free",
		"shop.gem_purchase.total": "Total: {amount} Gems",
		"shop.gem_purchase.price": "{price} ₽",
		"shop.gems_25.name": "25 Gems",
		"shop.gems_25.description": "25 gems for 24 ₽",
		"shop.gems_150.name": "150 Gems",
		"shop.gems_150.description": "100 gems + 50 free for 99 ₽",
		"shop.gems_500.name": "500 Gems",
		"shop.gems_500.description": "250 gems + 250 free for 249 ₽",
		"shop.gems_1500.name": "1500 Gems",
		"shop.gems_1500.description": "500 gems + 1000 free for 499 ₽",
		"shop.rewarded_gems_ad.reward_status": "+{amount} Gems!",
		"task.manual_damage_500.title": "Deal 500 Damage",
		"task.defeat_25_enemies.title": "Defeat 25 enemies",
		"task.defeat_2_elites.title": "Defeat 2 elite enemies",
		"task.defeat_1_boss.title": "Defeat 1 boss",
		"task.gain_10_hero_levels.title": "Buy 10 Levels",
		"task.hire_10_partners.title": "Hire 10 partners",
		"task.build_5_buildings.title": "Buy 5 buildings",
		"task.activate_autoclick_1.title": "Activate Autoclick 1 time",
		"task.gain_10_game_levels.title": "Reach 10 more stages",
		"ability.autoclick.name": "Autoclick",
		"ability.gold_bonus.name": "Gold Bonus",
		"ability.focus_burst.name": "Focus Burst",
		"ability.rally.name": "Rally",
		"ability.autoclick.effect": "Autoclick {hits}/s",
		"ability.gold_bonus.effect": "Gold x{multiplier}",
		"ability.focus_burst.effect": "Damage x{multiplier}",
		"ability.rally.effect": "DPS x{multiplier}",
		"ability.autoclick.duration": "Duration: {seconds}s",
		"ability.gold_bonus.duration": "Duration: {seconds}s",
		"ability.focus_burst.duration": "Duration: {seconds}s",
		"ability.rally.duration": "Duration: {seconds}s",
		"enemy.pool_01.enemy_01.name": "Naruto Uzumaki",
		"enemy.pool_01.enemy_02.name": "Sasuke Uchiha",
		"enemy.pool_01.enemy_03.name": "Sakura Haruno",
		"enemy.pool_01.enemy_04.name": "Rock Lee",
		"enemy.pool_01.enemy_05.name": "Neji Hyuga",
		"enemy.pool_01.enemy_06.name": "Ten-Ten",
		"enemy.pool_01.enemy_07.name": "Hinata Hyuga",
		"enemy.pool_01.enemy_08.name": "Kiba Inuzuka",
		"enemy.pool_01.enemy_09.name": "Shino Aburame",
		"enemy.pool_01.enemy_10.name": "Kankuro",
		"enemy.pool_01.enemy_11.name": "Temari",
		"enemy.pool_01.enemy_12.name": "Jirono",
		"enemy.pool_01.enemy_13.name": "Kidomaru",
		"enemy.pool_01.enemy_14.name": "Tauy",
		"enemy.pool_01.enemy_15.name": "Sakon and Ukon",
		"enemy.pool_01.elite_01.name": "Iruka Umino",
		"enemy.pool_01.elite_02.name": "Maito Guy",
		"enemy.pool_01.elite_03.name": "Kurenai Uhi",
		"enemy.pool_01.elite_04.name": "Baki",
		"enemy.pool_11.enemy_01.name": "Jugo",
		"enemy.pool_11.enemy_02.name": "Karin",
		"enemy.pool_11.enemy_03.name": "Suigetsu Hozuki",
		"enemy.pool_11.enemy_04.name": "Ino Yamanaka",
		"enemy.pool_11.enemy_05.name": "Shikamaru Nara",
		"enemy.pool_11.enemy_06.name": "Choji Akimichi",
		"enemy.pool_11.enemy_07.name": "Sai",
		"enemy.pool_11.enemy_08.name": "Sakura Haruno",
		"enemy.pool_11.enemy_09.name": "Naruto Uzumaki",
		"enemy.pool_11.enemy_10.name": "Sasuke Uchiha",
		"enemy.pool_11.enemy_11.name": "Yamato",
		"enemy.pool_11.enemy_12.name": "Konan",
		"enemy.pool_11.enemy_13.name": "Karui",
		"enemy.pool_11.enemy_14.name": "Darui",
		"enemy.pool_11.enemy_15.name": "Omoi",
		"enemy.pool_11.elite_01.name": "Asuma Sarutobi",
		"enemy.pool_11.elite_02.name": "Jiraya",
		"enemy.pool_11.elite_03.name": "Tsunade",
		"enemy.pool_11.elite_04.name": "Orochimaru",
		"enemy.pool_11.elite_05.name": "Itachi Uchiha",
		"enemy.pool_17.enemy_01.name": "Muu",
		"enemy.pool_17.enemy_02.name": "Oonoki",
		"enemy.pool_17.enemy_03.name": "Gengetsu Hozuki",
		"enemy.pool_17.enemy_04.name": "Mei Terumi",
		"enemy.pool_17.enemy_05.name": "Tobirama Senzu",
		"enemy.pool_17.enemy_06.name": "Hiruzen Sarutobi",
		"enemy.pool_17.enemy_07.name": "Killer B",
		"enemy.pool_17.enemy_08.name": "A (Third Raikage)",
		"enemy.pool_17.enemy_09.name": "A (Fourth Raikage)",
		"enemy.pool_17.elite_01.name": "Minato Namikaze",
		"enemy.pool_17.elite_02.name": "Hashirama Senzu",
		"enemy.pool_17.elite_03.name": "Maito Guy (8 Gates)",
		"ui.combat.gold_reward": "+{amount} Gold",
		"rewarded_ad.banner.available": "Watch Ad: Get Bonus",
		"rewarded_ad.banner.all_damage": "Watch Ad: x2 Damage",
		"rewarded_ad.banner.gems": "Watch Ad: +5 Gems",
		"rewarded_ad.banner.gold": "Watch Ad: x4 Gold",
		"rewarded_ad.banner.loading": "Loading Ad...",
		"rewarded_ad.banner.cooldown": "Bonus available soon",
		"rewarded_ad.banner.error": "Ad unavailable",
		"rewarded_ad.reward.all_damage": "All damage x2 for 60 seconds!",
		"rewarded_ad.reward.gems": "+5 Gems!",
		"rewarded_ad.reward.gold": "Gold x4 for 60 seconds!",
		"rewarded_ad.status.not_available": "Reward unavailable",
		"offline_reward.title": "Welcome back!",
		"offline_reward.time": "Away time: {time}",
		"offline_reward.reward": "+ {gold} Gold",
		"offline_reward.claim": "Claim",
		"offline_reward.claim_x3": "Watch Ad x3",
		"offline_reward.loading_ad": "Loading ad...",
		"settings.sound": "Sound",
		"settings.music": "Music",
		"settings.save_now": "Save Now",
		"settings.reset": "Reset",
		"settings.reset_confirm_title": "Reset all progress?",
		"settings.reset_confirm_description": "This will delete your save and start a new game.",
		"settings.version": "Version {version}",
		"auto_transition.title": "Auto-transition",
		"ui.gameplay.new_zone": "New Zone!",
		"ui.gameplay.level_up": "Level Up!",
		"common.duration.seconds": "{seconds}s",
		"common.duration.minutes": "{minutes}m",
		"common.duration.hours": "{hours}h",
		"common.duration.hours_minutes": "{hours}h {minutes}m",
	},
	"ru": {
		"ui.common.close": "Закрыть",
		"ui.common.buy": "Купить",
		"ui.common.cost": "Цена",
		"ui.common.reward": "Награда",
		"ui.common.level": "Уровень",
		"ui.common.cleared": "Пройдено",
		"ui.common.on": "Вкл",
		"ui.common.off": "Выкл",
		"ui.common.max": "Макс",
		"ui.common.purchased": "Куплено",
		"ui.common.in_progress": "В Процессе",
		"ui.common.claim": "Получить",
		"ui.common.claimed": "Получено",
		"ui.common.cancel": "Отмена",
		"ui.common.yes": "Да",
		"ui.common.no": "Нет",
		"ui.tab.upgrades": "Улучшения",
		"ui.tab.partners": "Команда",
		"ui.tab.settlement": "Деревня",
		"ui.tab.prestige": "Престиж",
		"ui.tab.shop": "Магазин",
		"ui.progress.boss_time": "Таймер Босса: {time}с",
		"ui.progress.enemies_count": "Врагов {current} / {required}",
		"ui.progress.hp_bar_value": "{current} / {max}",
		"ui.buy_mode.x1": "x1",
		"ui.buy_mode.x10": "x10",
		"ui.buy_mode.x100": "x100",
		"ui.buy_mode.max": "Макс",
		"settings.title": "Настройки",
		"settings.language": "Язык",
		"settings.language.en": "English",
		"settings.language.ru": "Русский",
		"settings.reset_progress": "Сброс Прогресса",
		"settings.confirm_reset": "Подтвердить Сброс",
		"settings.saved": "Сохранено",
		"settings.save_failed": "Ошибка Сохранения",
		"settings.progress_reset": "Сброс Прогресса",
		"auto_transition.status_on": "Вкл",
		"auto_transition.status_off": "Выкл",
		"auto_transition.description.line_1": "Когда включено",
		"auto_transition.description.line_2": "пройденные этапы",
		"auto_transition.description.line_3": "автоматически переходят",
		"auto_transition.description.line_4": "на следующий уровень",
		"skill_popup.hero.title": "Навык",
		"skill_popup.partner.title": "Навык партнёра",
		"skill_popup.requirement.hero_level": "Требуется {level} Ур",
		"skill_popup.requirement.ability_purchase": "Требуется {ability}",
		"skill_popup.requirement.partner_count": "Требуется {count}",
		"skill_popup.current.hero_level": "Сейчас: {current} / {required}",
		"skill_popup.current.partner_count": "Сейчас: {current} / {required}",
		"skill_popup.current.unlocked": "Открыто",
		"skill_popup.button.buy": "Купить: {cost}",
		"skill_popup.button.locked": "Закрыто",
		"skill_popup.button.purchased": "Куплено",
		"task.in_progress": "В Процессе",
		"task.claim": "Получить",
		"task.claimed": "Получено",
		"task.progress": "{current} / {target}",
		"task.reward": "Награда: {reward} Золота",
		"upgrade.hero.button": "x{count} - {cost}",
		"upgrade.hero.card.name": "Герой",
		"upgrade.hero.card.level_gain": "{level} Ур | +{gain} Урон",
		"upgrade.hero.card.damage": "Урон {damage}",
		"upgrade.hero.card.milestone_next": "x2 на {milestone} Ур",
		"upgrade.hero.card.milestone_max": "Максимум",
		"upgrade.ability.purchased": "Куплено",
		"upgrade.ability.requires_level": "Требуется {level} Ур",
		"upgrade.ability.buy": "Купить: {cost}",
		"upgrade.ability.card.name": "{name}",
		"upgrade.ability.card.rank": "Ранг {rank}/{max_rank}",
		"upgrade.ability.unlock_with_duration": "{duration}",
		"partner.hire_button": "x{count} - {cost}",
		"partner.card.name": "{name}",
		"partner.card.count_gain": "{count} | +{gain} Урон",
		"partner.card.total_dps": "Всего {total} DPS",
		"partner.card.milestone_next": "x2 на {milestone} Ур",
		"partner.card.milestone_max": "Максимум",
		"settlement.build_button": "x{count} - {cost}",
		"settlement.card.name": "{name}",
		"settlement.card.count": "Всего: {count}",
		"settlement.card.milestone_next": "x2 на {milestone} Ур",
		"settlement.card.milestone_max": "Максимум",
		"prestige.action": "Престиж",
		"prestige.action_card.title": "Престиж",
		"prestige.action_card.reward": "Получить +{points}",
		"prestige.action_card.reset_progress": "Сбросить прогресс",
		"prestige.action_card.get_points": "Получить очки",
		"prestige.talent_upgrade_bulk": "x{count} - {cost}",
		"prestige.card.name": "{name}",
		"prestige.card.count": "Кол-во: {count}",
		"prestige.card.empty": " ",
		"prestige.confirm.stage_level": "Этап",
		"prestige.confirm.character_level": "Уровень",
		"prestige.confirm.stage_points": "Очки этапа",
		"prestige.confirm.character_points": "Очки уровня",
		"prestige.confirm.points_to_gain": "Очки к получению: {points}",
		"prestige.confirm.available_after": "Доступно после",
		"prestige.confirm.total_earned_after": "Все заработано",
		"prestige.confirm.warning": "Весь прогресс будет сброшен",
		"prestige.confirm.talents_note": "Купленные таланты сохраняются",
		"prestige.confirm.title": "Престиж",
		"prestige.confirm.stage": "Этап: {stage}",
		"prestige.confirm.level": "Уровень: {level}",
		"prestige.confirm.reset_warning": "Весь прогресс будет сброшен",
		"prestige.confirm.talents_kept": "Таланты престижа сохраняются",
		"prestige.confirm.yes": "Да",
		"prestige.confirm.no": "Нет",
		"shop.buy_button": "Купить",
		"shop.confirm.title": "Подтвердите покупку",
		"shop.confirm.confirm": "Подтвердить",
		"shop.confirm.cancel": "Отмена",
		"zone.01.name": "Лес Скрытого Листа",
		"zone.02.name": "Тренировочная Площадка",
		"zone.03.name": "Лес Тумана",
		"zone.04.name": "Великий мост Наруто",
		"zone.05.name": "Лес Испытаний",
		"zone.06.name": "Лес Испытаний",
		"zone.07.name": "Лес Скрытого Листа",
		"zone.08.name": "Деревня Скрытого Листа",
		"zone.09.name": "Деревня Скрытого Листа",
		"zone.10.name": "Долина Завершения",
		"zone.11.name": "Пещера",
		"zone.12.name": "Пещера",
		"zone.13.name": "Лес Скрытого Листа",
		"zone.14.name": "Лес Скрытого Листа",
		"zone.15.name": "Деревня Скрытого Листа",
		"zone.16.name": "Зал Пяти Каге",
		"zone.17.name": "Поле Войны Шиноби",
		"zone.18.name": "Поле Войны Шиноби",
		"zone.19.name": "Поле Войны Шиноби",
		"zone.20.name": "Поле Войны Шиноби",
		"zone.21.name": "Поле Войны Шиноби",
		"zone.01.boss": "Мизуки",
		"zone.02.boss": "Какаши Хатаке",
		"zone.03.boss": "Хаку",
		"zone.04.boss": "Забуза Момочи",
		"zone.05.boss": "Кабуто Якуши",
		"zone.06.boss": "Орочимару",
		"zone.07.boss": "Гаара",
		"zone.08.boss": "Кисаме",
		"zone.09.boss": "Итачи Учиха",
		"zone.10.boss": "Саске Учиха",
		"zone.11.boss": "Сасори",
		"zone.12.boss": "Дейдара",
		"zone.13.boss": "Хидан",
		"zone.14.boss": "Какузу",
		"zone.15.boss": "Пейн",
		"zone.16.boss": "Саске Учиха",
		"zone.17.boss": "Тоби",
		"zone.18.boss": "Мадара Учиха",
		"zone.19.boss": "Мадара Джинчурики",
		"zone.20.boss": "Кагуя Ооцуцуки",
		"zone.21.boss": "Саске Учиха",
		"partner.01.name": "Наруто Узумаки",
		"partner.02.name": "Саске Учиха",
		"partner.03.name": "Сакура Харуно",
		"partner.04.name": "Какаши Хатаке",
		"partner.05.name": "Джирайя",
		"partner.06.name": "Орочимару",
		"partner.07.name": "Итачи Учиха",
		"partner.08.name": "Шесть Путей Пейна",
		"partner.09.name": "Конан",
		"partner.10.name": "Цунаде",
		"partner.11.name": "Итачи (Сусаноо)",
		"partner.12.name": "Муу",
		"partner.13.name": "Генгецу Хозуки",
		"partner.14.name": "Киллер Би",
		"partner.15.name": "Кабуто Якуши",
		"partner.16.name": "Эй (4ый Райкаге)",
		"partner.17.name": "Хирузен Сарутоби",
		"partner.18.name": "Тобирама Сенджу",
		"partner.19.name": "Эй (3ий Райкаге)",
		"partner.20.name": "Хаширама Сенджу",
		"partner.21.name": "Обито Учиха",
		"partner.22.name": "Мадара Учиха",
		"partner.23.name": "Минато Намикадзе",
		"partner.24.name": "Майто Гай",
		"partner.25.name": "Обито Джинчурики",
		"partner.26.name": "Мадара Джинчурики",
		"partner.27.name": "Саске Шесть Путей",
		"partner.28.name": "Наруто Шесть Путей",
		"building.01.name": "Тренировочное Поле",
		"building.02.name": "Резиденция Хокаге",
		"building.03.name": "Ичираку Рамен",
		"building.04.name": "Госпиталь",
		"building.05.name": "Академия Шиноби",
		"building.06.name": "Скала Хокаге",
		"building.01.purchase_gain": "+{bonus}% DPS",
		"building.01.total_bonus": "DPS +{bonus}%",
		"building.02.purchase_gain": "+{bonus}% Золота",
		"building.02.total_bonus": "Золото +{bonus}%",
		"building.03.purchase_gain": "+{bonus}% Урона",
		"building.03.total_bonus": "Урон +{bonus}%",
		"building.04.purchase_gain": "+{bonus}% Навыка",
		"building.04.total_bonus": "Навык +{bonus}%",
		"building.05.purchase_gain": "-{bonus}% CD",
		"building.05.total_bonus": "CD -{bonus}%",
		"building.06.purchase_gain": "+{bonus}% Золота Босса",
		"building.06.total_bonus": "Золото Босса +{bonus}%",
		"prestige.talent.01.name": "Мощь Каге",
		"prestige.talent.02.name": "Охотник",
		"prestige.talent.03.name": "Военачальник",
		"prestige.talent.04.name": "Быстрые руки",
		"prestige.talent.05.name": "Строитель",
		"prestige.talent.06.name": "Убийца Боссов",
		"prestige.talent.01.purchase_gain": "+{bonus}% Урона",
		"prestige.talent.01.total_bonus": "Урон +{bonus}%",
		"prestige.talent.02.purchase_gain": "+{bonus}% Золота",
		"prestige.talent.02.total_bonus": "Золото +{bonus}%",
		"prestige.talent.03.purchase_gain": "+{bonus}% DPS",
		"prestige.talent.03.total_bonus": "DPS +{bonus}%",
		"prestige.talent.04.purchase_gain": "+{bonus}% Автоклика",
		"prestige.talent.04.total_bonus": "Автоклик +{bonus}%",
		"prestige.talent.05.purchase_gain": "+{bonus}% Поселение",
		"prestige.talent.05.total_bonus": "Поселение +{bonus}%",
		"prestige.talent.06.purchase_gain": "+{bonus}% Урон Боссу",
		"prestige.talent.06.total_bonus": "Урон Боссу +{bonus}%",
		"shop.gold_pack_small.name": "Малый пакет золота",
		"shop.gold_pack_small.description": "5 часов золота",
		"shop.gold_pack_large.name": "Большой пакет золота",
		"shop.gold_pack_large.description": "24 часа золота",
		"shop.boss_retry_token.name": "",
		"shop.boss_retry_token.description": "",
		"shop.task_boost.name": "",
		"shop.task_boost.description": "",
		"shop.permanent_partner_dps_x2.name": "Вечный x2 DPS",
		"shop.permanent_partner_dps_x2.description": "Навсегда х2 DPS",
		"shop.permanent_click_damage_x2.name": "Вечный x2 Урон",
		"shop.permanent_click_damage_x2.description": "Навсегда x2 Урон",
		"shop.permanent_gold_x2.name": "Вечный x2 золото",
		"shop.permanent_gold_x2.description": "Навсегда х2 Золота",
		"shop.buy_button_count": "x{count} - {cost}",
		"shop.card.gold_reward": "Даёт +{amount} золота",
		"shop.card.partner_dps_multiplier": "Даёт DPS x{multiplier}",
		"shop.card.click_damage_multiplier": "Даёт Урон x{multiplier}",
		"shop.card.gold_multiplier": "Даёт Золото x{multiplier}",
		"shop.card.owned": "Всего: {count}",
		"shop.card.total_multiplier": "Бонус: x{multiplier}",
		"shop.rewarded_gems_ad.name": "Реклама: +3 гема",
		"shop.rewarded_gems_ad.description": "Гемы за рекламу",
		"shop.card.rewarded_gems": "+{amount} Гемов",
		"shop.button.watch_ad": "Смотреть",
		"shop.button.open": "Открыть",
		"shop.gem_purchase_entry.name": "Купить гемы",
		"shop.gem_purchase_entry.description": "Покупка гемов",
		"shop.card.gem_purchase_entry": "Купить гемы",
		"shop.gem_purchase.title": "Купить гемы",
		"shop.gem_purchase.invalid_product": "Неверный товар",
		"shop.gem_purchase.success": "+{amount} гемов!",
		"shop.gem_purchase.cancelled": "Покупка отменена",
		"shop.gem_purchase.error": "Ошибка покупки",
		"shop.gem_purchase.buy": "Купить",
		"shop.gem_purchase.amount_plain": "+{amount} гемов",
		"shop.gem_purchase.amount_bonus": "+{base} гемов +{bonus} бесплатно",
		"shop.gem_purchase.total": "Всего: {amount} гемов",
		"shop.gem_purchase.price": "{price} ₽",
		"shop.gems_25.name": "25 гемов",
		"shop.gems_25.description": "25 гемов за 24 ₽",
		"shop.gems_150.name": "150 гемов",
		"shop.gems_150.description": "100 гемов + 50 бесплатно за 99 ₽",
		"shop.gems_500.name": "500 гемов",
		"shop.gems_500.description": "250 гемов + 250 бесплатно за 249 ₽",
		"shop.gems_1500.name": "1500 гемов",
		"shop.gems_1500.description": "500 гемов + 1000 бесплатно за 499 ₽",
		"shop.rewarded_gems_ad.reward_status": "+{amount} гемов!",
		"task.manual_damage_500.title": "Нанести 500 Урона",
		"task.defeat_25_enemies.title": "Победить 25 врагов",
		"task.defeat_2_elites.title": "Победить 2 элитных врагов",
		"task.defeat_1_boss.title": "Победить 1 босса",
		"task.gain_10_hero_levels.title": "Купить 10 Уровней",
		"task.hire_10_partners.title": "Нанять 10 Партнеров",
		"task.build_5_buildings.title": "Купить 5 Строений",
		"task.activate_autoclick_1.title": "Активировать Автоклик 1 раз",
		"task.gain_10_game_levels.title": "Пройти 10 этапов",
		"ability.autoclick.name": "Автоклик",
		"ability.gold_bonus.name": "Бонус Золота",
		"ability.focus_burst.name": "Взрывной Урон",
		"ability.rally.name": "Боевой Клич",
		"ability.autoclick.effect": "Автоклик {hits}/с",
		"ability.gold_bonus.effect": "Золото x{multiplier}",
		"ability.focus_burst.effect": "Урон x{multiplier}",
		"ability.rally.effect": "DPS x{multiplier}",
		"ability.autoclick.duration": "Длительность: {seconds}с",
		"ability.gold_bonus.duration": "Длительность: {seconds}с",
		"ability.focus_burst.duration": "Длительность: {seconds}с",
		"ability.rally.duration": "Длительность: {seconds}с",
		"enemy.pool_01.enemy_01.name": "Наруто Узумаки",
		"enemy.pool_01.enemy_02.name": "Саске Учиха",
		"enemy.pool_01.enemy_03.name": "Сакура Харуно",
		"enemy.pool_01.enemy_04.name": "Рок Ли",
		"enemy.pool_01.enemy_05.name": "Неджи Хьюга",
		"enemy.pool_01.enemy_06.name": "Тен-Тен",
		"enemy.pool_01.enemy_07.name": "Хината Хьюга",
		"enemy.pool_01.enemy_08.name": "Киба Инузука",
		"enemy.pool_01.enemy_09.name": "Шино Абураме",
		"enemy.pool_01.enemy_10.name": "Канкуро",
		"enemy.pool_01.enemy_11.name": "Темари",
		"enemy.pool_01.enemy_12.name": "Джиробо",
		"enemy.pool_01.enemy_13.name": "Кидомару",
		"enemy.pool_01.enemy_14.name": "Таюи",
		"enemy.pool_01.enemy_15.name": "Сакон и Укон",
		"enemy.pool_01.elite_01.name": "Ирука Умино",
		"enemy.pool_01.elite_02.name": "Майто Гай",
		"enemy.pool_01.elite_03.name": "Куренай Юхи",
		"enemy.pool_01.elite_04.name": "Баки",
		"enemy.pool_11.enemy_01.name": "Джуго",
		"enemy.pool_11.enemy_02.name": "Карин",
		"enemy.pool_11.enemy_03.name": "Суйгетцу Хозуки",
		"enemy.pool_11.enemy_04.name": "Ино Яманака",
		"enemy.pool_11.enemy_05.name": "Шикамару Нара",
		"enemy.pool_11.enemy_06.name": "Чоджи Акимичи",
		"enemy.pool_11.enemy_07.name": "Сай",
		"enemy.pool_11.enemy_08.name": "Сакура Харуно",
		"enemy.pool_11.enemy_09.name": "Наруто Узумаки",
		"enemy.pool_11.enemy_10.name": "Саске Учиха",
		"enemy.pool_11.enemy_11.name": "Ямато",
		"enemy.pool_11.enemy_12.name": "Конан",
		"enemy.pool_11.enemy_13.name": "Каруи",
		"enemy.pool_11.enemy_14.name": "Даруи",
		"enemy.pool_11.enemy_15.name": "Омои",
		"enemy.pool_11.elite_01.name": "Асума Сарутоби",
		"enemy.pool_11.elite_02.name": "Джирая",
		"enemy.pool_11.elite_03.name": "Цунаде",
		"enemy.pool_11.elite_04.name": "Орочимару",
		"enemy.pool_11.elite_05.name": "Итачи Учиха",
		"enemy.pool_17.enemy_01.name": "Муу",
		"enemy.pool_17.enemy_02.name": "Ооноки",
		"enemy.pool_17.enemy_03.name": "Генгецу Хозуки",
		"enemy.pool_17.enemy_04.name": "Мей Теруми",
		"enemy.pool_17.enemy_05.name": "Тобирама Сенджу",
		"enemy.pool_17.enemy_06.name": "Хирузен Сарутоби",
		"enemy.pool_17.enemy_07.name": "Киллер Би",
		"enemy.pool_17.enemy_08.name": "Эй (Третий Райкаге)",
		"enemy.pool_17.enemy_09.name": "Эй (Четвертый Райкаге)",
		"enemy.pool_17.elite_01.name": "Минато Намикадзе",
		"enemy.pool_17.elite_02.name": "Хаширама Сенджу",
		"enemy.pool_17.elite_03.name": "Майто Гай (8 Врат)",
		"ui.combat.gold_reward": "+{amount} Золота",
		"rewarded_ad.banner.available": "Смотреть рекламу: Получи бонус",
		"rewarded_ad.banner.all_damage": "Реклама: x2 урон",
		"rewarded_ad.banner.gems": "Реклама: +5 гемов",
		"rewarded_ad.banner.gold": "Реклама: x4 золото",
		"rewarded_ad.banner.loading": "Загрузка рекламы...",
		"rewarded_ad.banner.cooldown": "Бонус скоро будет доступен",
		"rewarded_ad.banner.error": "Реклама недоступна",
		"rewarded_ad.reward.all_damage": "Весь урон x2 на 60 секунд!",
		"rewarded_ad.reward.gems": "+5 гемов!",
		"rewarded_ad.reward.gold": "Золото x4 на 60 секунд!",
		"rewarded_ad.status.not_available": "Награда недоступна",
		"offline_reward.title": "С возвращением!",
		"offline_reward.time": "Вне игры: {time}",
		"offline_reward.reward": "+ {gold} золота",
		"offline_reward.claim": "Получить",
		"offline_reward.claim_x3": "Реклама x3",
		"offline_reward.loading_ad": "Загрузка рекламы...",
		"settings.sound": "Звук",
		"settings.music": "Музыка",
		"settings.save_now": "Сохранить",
		"settings.reset": "Сброс",
		"settings.reset_confirm_title": "Сбросить весь прогресс?",
		"settings.reset_confirm_description": "Это удалит прогресс и начнёт новую игру.",
		"settings.version": "Версия {version}",
		"auto_transition.title": "Авто-переход",
		"ui.gameplay.new_zone": "Новая Зона!",
		"ui.gameplay.level_up": "Новый Уровень!",
		"common.duration.seconds": "{seconds}с",
		"common.duration.minutes": "{minutes}м",
		"common.duration.hours": "{hours}ч",
		"common.duration.hours_minutes": "{hours}ч {minutes}м",
	},
}


static func get_translations() -> Dictionary:
	return TRANSLATIONS.duplicate(true)
